from skfolio.measures import (
    PerfMeasure,
    RiskMeasure,
    ExtraRiskMeasure,
    RatioMeasure,
)

SHARPE_RATIO = SHARPE = RatioMeasure.SHARPE_RATIO
ANNUALIZED_SHARPE_RATIO = ANNUALIZED_SHARPE = RatioMeasure.ANNUALIZED_SHARPE_RATIO
SORTINO_RATIO = SORTINO = RatioMeasure.SORTINO_RATIO
CALMAR_RATIO = CALMAR = RatioMeasure.CALMAR_RATIO
ANNUALIZED_SORTINO_RATIO = ANNUALIZED_SORTINO = RatioMeasure.ANNUALIZED_SORTINO_RATIO
MAX_DRAWDOWN = MAX_DD = MDD = RiskMeasure.MAX_DRAWDOWN
AVERAGE_DRAWDOWN = AVG_DD = RiskMeasure.AVERAGE_DRAWDOWN
CVAR = RiskMeasure.CVAR
VALUE_AT_RISK = VAR = ExtraRiskMeasure.VALUE_AT_RISK
MEAN = PerfMeasure.MEAN
ANNUALIZED_MEAN = PerfMeasure.ANNUALIZED_MEAN
VARIANCE = RiskMeasure.VARIANCE
STANDARD_DEVIATION = STD = RiskMeasure.STANDARD_DEVIATION
SEMI_DEVIATION = RiskMeasure.SEMI_DEVIATION
