from skfolio.measures import (
    PerfMeasure,
    RiskMeasure,
    ExtraRiskMeasure,
    RatioMeasure,
)

# === PerfMeasure ===
MEAN = PerfMeasure.MEAN
ANNUALIZED_MEAN = PerfMeasure.ANNUALIZED_MEAN

# === RiskMeasure ===
VARIANCE = RiskMeasure.VARIANCE
ANNUALIZED_VARIANCE = RiskMeasure.ANNUALIZED_VARIANCE
SEMI_VARIANCE = RiskMeasure.SEMI_VARIANCE
ANNUALIZED_SEMI_VARIANCE = RiskMeasure.ANNUALIZED_SEMI_VARIANCE
STANDARD_DEVIATION = STD = RiskMeasure.STANDARD_DEVIATION
ANNUALIZED_STANDARD_DEVIATION = ANNUALIZED_STD = RiskMeasure.ANNUALIZED_STANDARD_DEVIATION
SEMI_DEVIATION = RiskMeasure.SEMI_DEVIATION
ANNUALIZED_SEMI_DEVIATION = RiskMeasure.ANNUALIZED_SEMI_DEVIATION
MEAN_ABSOLUTE_DEVIATION = MAD = RiskMeasure.MEAN_ABSOLUTE_DEVIATION
CVAR = RiskMeasure.CVAR
EVAR = RiskMeasure.EVAR
WORST_REALIZATION = RiskMeasure.WORST_REALIZATION
CDAR = RiskMeasure.CDAR
MAX_DRAWDOWN = MAX_DD = MDD = RiskMeasure.MAX_DRAWDOWN
AVERAGE_DRAWDOWN = AVG_DD = RiskMeasure.AVERAGE_DRAWDOWN
EDAR = RiskMeasure.EDAR
FIRST_LOWER_PARTIAL_MOMENT = FLPM = RiskMeasure.FIRST_LOWER_PARTIAL_MOMENT
ULCER_INDEX = RiskMeasure.ULCER_INDEX
GINI_MEAN_DIFFERENCE = RiskMeasure.GINI_MEAN_DIFFERENCE

# === ExtraRiskMeasure ===
VALUE_AT_RISK = VAR = ExtraRiskMeasure.VALUE_AT_RISK
DRAWDOWN_AT_RISK = DAR = ExtraRiskMeasure.DRAWDOWN_AT_RISK
ENTROPIC_RISK_MEASURE = ExtraRiskMeasure.ENTROPIC_RISK_MEASURE
FOURTH_CENTRAL_MOMENT = ExtraRiskMeasure.FOURTH_CENTRAL_MOMENT
FOURTH_LOWER_PARTIAL_MOMENT = ExtraRiskMeasure.FOURTH_LOWER_PARTIAL_MOMENT
SKEW = ExtraRiskMeasure.SKEW
KURTOSIS = ExtraRiskMeasure.KURTOSIS

# === RatioMeasure ===
SHARPE_RATIO = SHARPE = RatioMeasure.SHARPE_RATIO
ANNUALIZED_SHARPE_RATIO = ANNUALIZED_SHARPE = RatioMeasure.ANNUALIZED_SHARPE_RATIO
SORTINO_RATIO = SORTINO = RatioMeasure.SORTINO_RATIO
ANNUALIZED_SORTINO_RATIO = ANNUALIZED_SORTINO = RatioMeasure.ANNUALIZED_SORTINO_RATIO
MEAN_ABSOLUTE_DEVIATION_RATIO = MAD_RATIO = RatioMeasure.MEAN_ABSOLUTE_DEVIATION_RATIO
FIRST_LOWER_PARTIAL_MOMENT_RATIO = FLPM_RATIO = RatioMeasure.FIRST_LOWER_PARTIAL_MOMENT_RATIO
VALUE_AT_RISK_RATIO = VAR_RATIO = RatioMeasure.VALUE_AT_RISK_RATIO
CVAR_RATIO = RatioMeasure.CVAR_RATIO
ENTROPIC_RISK_MEASURE_RATIO = RatioMeasure.ENTROPIC_RISK_MEASURE_RATIO
EVAR_RATIO = RatioMeasure.EVAR_RATIO
WORST_REALIZATION_RATIO = RatioMeasure.WORST_REALIZATION_RATIO
DRAWDOWN_AT_RISK_RATIO = DAR_RATIO = RatioMeasure.DRAWDOWN_AT_RISK_RATIO
CDAR_RATIO = RatioMeasure.CDAR_RATIO
CALMAR_RATIO = CALMAR = RatioMeasure.CALMAR_RATIO
AVERAGE_DRAWDOWN_RATIO = AVG_DD_RATIO = RatioMeasure.AVERAGE_DRAWDOWN_RATIO
EDAR_RATIO = RatioMeasure.EDAR_RATIO
ULCER_INDEX_RATIO = RatioMeasure.ULCER_INDEX_RATIO
GINI_MEAN_DIFFERENCE_RATIO = RatioMeasure.GINI_MEAN_DIFFERENCE_RATIO
